package io.openfuture.chain.core.exception

class ChainOutOfSyncException : Exception()